on:
  push:
    branches:
      - main

name: Create Release

jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Build docker image
        run: docker build . -t tt
      - name: Generate font
        run: docker run  -v ${PWD}:/font  tt
      - name: Update website
        run: |
          git config --global user.name 'Yefu Wang'
          git config --global user.email 'yefuwang@users.noreply.github.com'
          cp SbsSlim.woff2 docs
          cp SbsSlim.woff docs
          cp SbsSlim.otf docs
          cp SbsSlim.ttf docs
          git add -f ./docs/SbsSlim.*
          git commit -m "From Github Actions: automatically release the latest font"
          git push
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: Release ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: false
      - name: Upload TTF
        id: upload-ttf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./SbsSlim.ttf
          asset_name: SbsSlim.ttf
          asset_content_type: font/ttf
      - name: Upload OTF
        id: upload-otf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./SbsSlim.otf
          asset_name: SbsSlim.otf
          asset_content_type: font/otf
      - name: Upload WOFF
        id: upload-woff
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SbsSlim.woff
          asset_name: SbsSlim.woff
          asset_content_type: font/woff
      - name: Upload WOFF2
        id: upload-woff2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SbsSlim.woff2
          asset_name: SbsSlim.woff2
          asset_content_type: font/woff2
